// app/layout.tsx
import "~/styles/globals.css"; // Add your global styles
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en" className="bg-black text-white">
      <body className="flex flex-col min-h-screen">
        {/* Include Header */}
        <Header />

        {/* Spacer for Fixed Header */}
        <div className="h-20"></div>

        {/* Main Content */}
        <main className="flex-grow">{children}</main>

        {/* Include Footer */}
        <Footer />
      </body>
    </html>
  );
}
